### ISSUE TITLE
Factions Duplicate territory messages

### ISSUE THREAD

**Issue by DraksterAU** [TCPR/Fixes#3]
Hey @Robotia well done on finally fixing up the commandsender bug!!! =D

I just wanted to let you know of the only other bug in Factions I know of, just in case you're ever able to fix it...

Every time you switch territories in KCauldron, you get a duplicate "Wilderness - its a Free for all here" or "Faction - Welcome to our territory" style message.

Has happened since an update to Cauldron in v1.7.10 (around the 1200 forge version mark).
It occurs with all Factions versions.

Doesnt happen in Craftbukkit, bukkit or spigot, though.

Not a game breaker, but clearly you know what you're doing so!

**Comment by Robotia** [comment]
@DraksterAU Try out Thermos https://github.com/TCPR/Thermos and see if that fixes things

**Comment by DraksterAU** [comment]
Wow.... Thanks for the quick response! 

I'll test it shortly! :D

**Comment by Robotia** [comment]
Sure!

**Comment by DraksterAU** [comment]
@Robotia This still occurs in the latest build of Thermos I'm afraid.

I also get a lot of issues from LegendQuest 1.9.7 when I try to use thermos, the playerInteractEvent is throwing errors constantly in the logs.

[09:10:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to LegendQuest v1.9.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.UNOFFICIAL]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:218) [ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick2(TileActivator.java:434) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:401) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:217) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:176) [TileActivator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2528) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2233) ~[?:?]
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2227) ~[?:?]
        at me.sablednah.legendquest.listeners.SkillLinkEvents.onInteract(SkillLinkEvents.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
        ... 16 more

**Comment by Robotia** [comment]
The duplicate messages are an issue with Thermos that I will be fixing this Friday afternoon, sorry about that!

**Comment by DraksterAU** [comment]
No worries mate :)

Hope you can see what's wrong with LQ too.... Haha... :/

**Comment by DraksterAU** [comment]
@Robotia Hey Robo, Is the latest build available for thermos what you'd consider stable + Contain the fix for duplicate chat messages? :P haha

**Comment by Robotia** [comment]
It is indeed

**Comment by DraksterAU** [comment]
@Robotia Does it fix the dupe messages? :P

**Comment by Robotia** [comment]
Yes, that was because of interaction event doubling. It was fixed about a week ago in ~B13 I believe.

**Comment by DraksterAU** [comment]
Woooot! Ill test it out now :D

**Comment by DraksterAU** [comment]
@Robotia Negative... still a bug..

**Comment by DraksterAU** [comment]
Closing this one, as it is no longer a problem (both Markehme's plugin and my manual fix work)
